#!/bin/bash

list=$1
threads=4
#threadsX2=$((${threads}*2))

#adni=/ifs/scratch/pimri/posnerlab/1anal/adni

#CMD_batch=/ifs/scratch/pimri/posnerlab/1anal/adni/adni_on_c2b2/job/cmd1.batch.trac.${list}
#rm -rf $CMD_batch

for s in `cat /ifs/scratch/pimri/posnerlab/1anal/FTO/code_fto_c2b2/\$list`
do
#s=`echo $SUBJECT | egrep -o '[0-9]{8}'`
CMD=/ifs/scratch/pimri/posnerlab/1anal/FTO/code_fto_c2b2/job/cmd1.trac.${s}
rm -rf $CMD
datafolder=/ifs/scratch/pimri/posnerlab/1anal/FTO/rawdata
SUBJECT=${s}
echo ${SUBJECT}

cat<<EOC >$CMD
#!/bin/bash
#$ -cwd -S /bin/bash -j y
#$ -pe smp 2
#$ -l mem=3G,time=3::
#$ -l gpu=3
#$ -M jc4248@c2b2.columbia.edu -m bes

#CUDA
unset LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nfs/apps/cuda/7.5.18/lib64
#export PATH=${PATH}:/nfs/apps/cuda/7.5.18/bin
export FSLGECUDAQ=gpu_1d.q

source ~/.bashrc
echo $LD_LIBRARY_PATH

mkdir -p /tmp/${s}/
cd /tmp/${s}
cp /ifs/scratch/pimri/posnerlab/1anal/FTO/data/slspec_fto.txt ./

echo current folder is \`pwd\`
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$threads
#%% 1. setup %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#cp -f $datafolder/${s}_mr_dwi.mif.gz mr_dwi.mif.gz
echo mrconvert
time mrconvert $datafolder/${s}_rawdti.nii.gz -force mr_dwi.mif.gz -fslgrad $datafolder/bvec $datafolder/bval \
            -datatype float32 -stride 0,0,0,1 -nthreads ${threads}

    echo dwidenoise
    time dwidenoise mr_dwi.mif.gz -force mr_dwi_denoised.mif.gz -nthreads ${threads} 
 sleep 0.1
 
 echo mrdegibss
    time mrdegibbs mr_dwi_denoised.mif.gz mr_dwi_denoised_gibbs.mif.gz -force -nthreads ${threads} 
sleep 0.1

	time dwipreproc mr_dwi_denoised_gibbs.mif.gz mr_dwi_denoised_gibbs_preproc.mif.gz \
-pe_dir AP \
-rpe_none \
-readout_time 0.18462 \
-eddy_options " --repol --niter=8 --data_is_shelled --fwhm=10,8,4,2,0,0,0,0 --repol --out=eddy_corrected_data --mporder=6 --slspec=../slspec_fto.txt --s2v_niter=5 --s2v_lambda=1 --s2v_interp=trilinear " \
-nthreads ${threads} \
-nocleanup -force -cuda
 sleep 0.1
  
  dwiextract mr_dwi_denoised_gibbs_preproc.mif.gz - -bzero -nthreads ${threads} | mrmath - mean \
                -force mr_meanb0.mif.gz -axis 3 -quiet -nthreads ${threads} 
sleep 0.1
cp -f mr_meanb0.mif.gz mr_meanb0_nonbiascorr.mif.gz 
	mrconvert mr_meanb0_nonbiascorr.mif.gz mr_meanb0_nonbiascorr.nii.gz -force -quiet -nthreads ${threads}
sleep 0.1
     #pigz --fast -b 1280 -f mr_meanb0_nonbiascorr.nii
     bet2 mr_meanb0_nonbiascorr mr_meanb0_nonbiascorr_bet2 -m -f 0.1 -v
sleep 0.1
     
     dwi2mask mr_dwi_denoised_gibbs_preproc.mif.gz mr_dwi_mask.mif.gz -force -nthreads ${threads} 
            #pigz --fast -b 1280 -f mr_dwi_mask.mif
  sleep 0.1
          
     dwi2mask mr_dwi_denoised_gibbs_preproc.mif.gz - -nthreads ${threads} -quiet | maskfilter - erode \
     -npass 3 -force mr_eroded_mask.mif.gz -quiet -nthreads ${threads}
sleep 0.1
            #pigz --fast -b 1280 -f mr_eroded_mask.mif
#fi
#%% 6. bias field correction (time: 0.5m)
#if [ ! -e mr_dwi_denoised_gibbs_crop_preproc_biasCorr.mif.gz ]; then
     echo dwibiascorrect
     time dwibiascorrect mr_dwi_denoised_gibbs_preproc.mif.gz -force mr_dwi_denoised_gibbs_preproc_biasCorr.mif.gz -ants \
     -nthreads ${threads} -mask mr_meanb0_nonbiascorr_bet2_mask.nii.gz 
sleep 0.1
            #pigz --fast -b 1280 -f mr_dwi_denoised_gibbs_crop_preproc_biasCorr.mif
     mrconvert mr_meanb0_nonbiascorr_bet2_mask.nii.gz mr_meanb0_nonbiascorr_bet2_mask.mif.gz -force -nthreads ${threads}
sleep 0.1
            #pigz --fast -b 1280 -f mr_meanb0_nonbiascorr_bet2_mask.mif
#fi
#%% 7. generating b0 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#if [ ! -e mr_meanb0.mif.gz ];then
     dwiextract mr_dwi_denoised_gibbs_preproc_biasCorr.mif.gz - -bzero -quiet -nthreads ${threads} | mrmath - mean \
     	-force mr_meanb0.mif.gz -axis 3 -quiet -nthreads ${threads} 
sleep 0.1
     mrconvert mr_meanb0.mif.gz mr_meanb0.nii.gz -force -quiet -nthreads ${threads}
  sleep 0.1
   
     bet2 mr_meanb0 mr_meanb0_bet -m -f 0.2
sleep 0.1
     
     mrresize mr_meanb0_bet.nii.gz -voxel 1.25 mr_meanb0_bet_upsample125.nii.gz \
     	-force -interp sinc -nthreads ${threads} -quiet
sleep 0.1
     mrresize mr_meanb0_bet_mask.nii.gz -voxel 1.25 mr_meanb0_bet_mask_upsample125.nii.gz \
     	-force -interp sinc -nthreads ${threads} -quiet
sleep 0.1
     
     #&& pigz --fast -b 1280 -f mr_meanb0.mif
#fi
#% make sure to use "DILATED MASK" for FOD generation
#if [ ! -e mr_dilate_mask.mif.gz ];then
#    dwi2mask mr_dwi_denoised_gibbs_crop_preproc_biasCorr.mif - -nthreads 256 
#fi
#%% 8. upsampling %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for im in mr_dwi_denoised_gibbs_preproc_biasCorr mr_meanb0_nonbiascorr_bet2_mask mr_meanb0;
do 
     	mrresize \${im}.mif.gz -voxel 1.25 -force \${im}_upsample125.mif.gz -interp sinc -nthreads ${threads} -quiet
sleep 0.1
done
#% make sure to use "DILATED MASK" for FOD generation
#if [ ! -e mr_dilate_mask.mif.gz ];then
    dwi2mask mr_dwi_denoised_gibbs_preproc_biasCorr_upsample125.mif.gz - -quiet -nthreads ${threads} | maskfilter - dilate \
    -npass 3 mr_dilate_mask_upsample125.mif.gz -force -quiet -nthreads ${threads} 
            #&& pigz --fast -b 1280 -f mr_dilate_mask_upsample125.mif
sleep 0.1
    
    dwi2mask mr_dwi_denoised_gibbs_preproc_biasCorr_upsample125.mif.gz mr_mask_upsample125.mif.gz -nthreads ${threads} -force 
            #pigz --fast -b 1280 -f mr_mask_upsample125.mif
sleep 0.1
    
    mrconvert mr_dwi_denoised_gibbs_preproc_biasCorr_upsample125.mif.gz \
            mr_dwi_denoised_gibbs_preproc_biasCorr_upsample125.nii.gz -force -nthreads ${threads}
sleep 0.1
    
    bet2 mr_dwi_denoised_gibbs_preproc_biasCorr_upsample125 \
            mr_dwi_denoised_gibbs_preproc_biasCorr_upsample125_bet2 -m -f 0.2 -v
sleep 0.1
#fi
##########################################################################################################################################
##################Preparation for 5TT using freesurfer APARC+ASEG ############################################################



######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
###tckgen and connectome (time for 1M = 
#  time tckgen WM_FODs_upsample125_norm.mif.gz mr_track_20M_${s}.tck -act 5tt_freesurfer2diff_upsample125.mif.gz \
#            -backtrack -crop_at_gmwmi -seed_dynamic WM_FODs_upsample125_norm.mif.gz -angle 22.5 -maxlength 250 -minlength 10 \
#            -power 1.0 -select 20M -force -nthreads ${threads} && echo 'tckgen done'**********
#  tcksift -act 5tt_freesurfer2diff_upsample125.mif mr_track_20M_${s}.tck WM_FODs.mif mr_track_10M_SIFT_${s}.tck \
#            -term_number 10M -force -nthreads ${threads} && echo 'sift done'*******
## FA, MD, MO, AD (L1), RD (L2+L3/2)            
#tcksample mr_track_10M_SIFT.tck dtifit_FA.nii mr_track_10M_SIFT_mean_FA.csv -stat_tck mean -force -nthreads ${threads}
#tcksample mr_track_10M_SIFT.tck dtifit_MD.nii mr_track_10M_SIFT_mean_MD.csv -stat_tck mean -force -nthreads ${threads}
#tcksample mr_track_10M_SIFT.tck dtifit_MO.nii mr_track_10M_SIFT_mean_MO.csv -stat_tck mean -force -nthreads ${threads}
#tcksample mr_track_10M_SIFT.tck dtifit_L1.nii mr_track_10M_SIFT_mean_AD.csv -stat_tck mean -force -nthreads ${threads}
#            fslmaths dtifit_L2 -add dtifit_L3 -div 2 dtifit_RD
#tcksample mr_track_10M_SIFT.tck dtifit_RD.nii mr_track_10M_SIFT_mean_RD.csv -stat_tck mean -force -nthreads ${threads}
#### tck2connectome
#for im in aparc+aseg aparc.a2009s+aseg
#do
#tck2connectome -force -zero_diagonal -nthreads ${threads} \
#            mr_track_10M_SIFT_${s}.tck nodes_\${im}.mif mr_sift_10M_connectome_\${im}_count.csv
            
#tck2connectome -force -zero_diagonal -scale_length -stat_edge mean mr_track_10M_SIFT_${s}.tck nodes_\${im}.mif \
#            mr_sift_10M_connectome_\${im}_length.csv -nthreads ${threads} 
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_FA.csv -nthreads ${threads} \
#            mr_track_10M_SIFT_${s}.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_FA.csv
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_MD.csv -nthreads ${threads} \
#            mr_track_10M_SIFT_${s}.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_MD.csv
            
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_MO.csv -nthreads ${threads} \
#            mr_track_10M_SIFT_${s}.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_MO.csv
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_AD.csv -nthreads ${threads} \
#            mr_track_10M_SIFT_${s}.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_AD.csv
            
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_RD.csv -nthreads ${threads} \
#            mr_track_10M_SIFT_${s}.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_RD.csv
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
     
            

#### COPY ALL THE FILES TO SCRATCH ####
#cp -rfv ../dwi /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/fs/${s}/
#######################################################################
# pigz#
#pigz --best -b 1280 -f -T -p ${threads} *mif
#pigz --best -b 1280 -f -T -p ${threads} *nii
cp -rfv /tmp/${s} /ifs/scratch/pimri/posnerlab/1anal/FTO/subjects
echo "I THINK EVERYTHING IS DONE BY NOW"
EOC


chmod +x $CMD
qsub $CMD
done


### batch submission

#echo $CMD_batch
#$code/fsl_sub_hpc_2 -s smp,$threads -l /ifs/scratch/pimri/posnerlab/1anal/adni/adni_on_c2b2/job -t $CMD_batch
#$code/fsl_sub_hpc_6 -l /ifs/scratch/pimri/posnerlab/1anal/adni/adni_on_c2b2/job -t $CMD_batch
